name: Main

on:
  push:
    branches: 
      - master

jobs:
  linter:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          
      - name: Run Tests
        run: dotnet test Tests
