name: Main

on:
  push:
    branches: 
      - master

jobs:
  linter:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          
      - name: Run Tests
        run: dotnet test Tests
        
      - name: Build Demo
        run: dotnet publish -c Release --self-contained false -r win10-x64

      - name: Upload Demo
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: ./Demo/bin
